using Karartek.Entities.Concrete;


namespace Karartek.DataAccess.Concrete.EntityFramework.Context.Seed
{
    internal static class CitySeeds
    {
        internal static readonly List<City> cities = new List<City>()
        {
            new City() { Id = 1, Name = "Adana", OrderIndex = 1 ,PlateCode = "01" },
            new City() { Id = 2, Name = "Adıyaman", OrderIndex = 2 ,PlateCode = "02" },
            new City() { Id = 3, Name = "Afyonkarahisar", OrderIndex = 3 ,PlateCode = "03" },
            new City() { Id = 4, Name = "Ağrı", OrderIndex = 4 ,PlateCode = "04" },
            new City() { Id = 5, Name = "Amasya", OrderIndex = 5 ,PlateCode = "05" },
            new City() { Id = 6, Name = "Ankara", OrderIndex = 6 ,PlateCode = "06" },
            new City() { Id = 7, Name = "Antalya", OrderIndex = 7 ,PlateCode = "07" },
            new City() { Id = 8, Name = "Artvin", OrderIndex = 8 ,PlateCode = "08" },
            new City() { Id = 9, Name = "Aydın", OrderIndex = 9 ,PlateCode = "09" },
            new City() { Id = 10, Name = "Balıkesir", OrderIndex = 10,PlateCode = "10" },
            new City() { Id = 11, Name = "Bilecik", OrderIndex = 11,PlateCode = "11" },
            new City() { Id = 12, Name = "Bingöl", OrderIndex = 12,PlateCode = "12" },
            new City() { Id = 13, Name = "Bitlis", OrderIndex = 13,PlateCode = "13" },
            new City() { Id = 14, Name = "Bolu", OrderIndex = 14,PlateCode = "14" },
            new City() { Id = 15, Name = "Burdur", OrderIndex = 15,PlateCode = "15" },
            new City() { Id = 16, Name = "Bursa", OrderIndex = 16,PlateCode = "16" },
            new City() { Id = 17, Name = "Çanakkale", OrderIndex = 17,PlateCode = "17" },
            new City() { Id = 18, Name = "Çankırı", OrderIndex = 18,PlateCode = "18" },
            new City() { Id = 19, Name = "Çorum", OrderIndex = 19,PlateCode = "19" },
            new City() { Id = 20, Name = "Denizli", OrderIndex = 20,PlateCode = "20" },
            new City() { Id = 21, Name = "Diyarbakır", OrderIndex = 21,PlateCode = "21" },
            new City() { Id = 22, Name = "Edirne", OrderIndex = 22,PlateCode = "22" }  ,
            new City() { Id = 23, Name = "Elazığ", OrderIndex = 23,PlateCode = "23" } ,
            new City() { Id = 24, Name = "Erzincan", OrderIndex = 24,PlateCode = "24" }  ,
            new City() { Id = 25, Name = "Erzurum", OrderIndex = 25,PlateCode = "25" }  ,
             new City() { Id = 26, Name = "Eskişehir", OrderIndex = 26,PlateCode = "26" }  ,
             new City() { Id = 27, Name = "Gaziantep", OrderIndex = 27,PlateCode = "27" }  ,
             new City() { Id = 28, Name = "Giresun", OrderIndex = 28,PlateCode = "28" }  ,
             new City() { Id = 29, Name = "Gümüşhane", OrderIndex = 29,PlateCode = "29" } ,
             new City() { Id = 30, Name = "Hakkari", OrderIndex = 30,PlateCode = "30" }  ,
             new City() { Id = 31, Name = "Hatay", OrderIndex = 31,PlateCode = "31" }  ,
             new City() { Id = 32, Name = "Isparta", OrderIndex = 32,PlateCode = "32" } ,
             new City() { Id = 33, Name = "Mersin", OrderIndex = 33,PlateCode = "33" },
             new City() { Id = 34, Name = "İstanbul", OrderIndex = 34,PlateCode = "34" }  ,
             new City() { Id = 35, Name = "İzmir", OrderIndex = 35,PlateCode = "35" }  ,
             new City() { Id = 36, Name = "Kars", OrderIndex = 36,PlateCode = "36" }  ,
             new City() { Id = 37, Name = "Kastamonu", OrderIndex = 37,PlateCode = "37" } ,
             new City() { Id = 38, Name = "Kayseri", OrderIndex = 38,PlateCode = "38" }  ,
             new City() { Id = 39, Name = "Kırklareli", OrderIndex = 39,PlateCode = "39" } ,
             new City() { Id = 40, Name = "Kırşehir", OrderIndex = 40,PlateCode = "40" }  ,
             new City() { Id = 41, Name = "Kocaeli", OrderIndex = 41,PlateCode = "41" }  ,
             new City() { Id = 42, Name = "Konya", OrderIndex = 42,PlateCode = "42" }  ,
             new City() { Id = 43, Name = "Kütahya", OrderIndex = 43,PlateCode = "43" }  ,
             new City() { Id = 44, Name = "Malatya", OrderIndex = 44,PlateCode = "44" }  ,
             new City() { Id = 45, Name = "Manisa", OrderIndex = 45,PlateCode = "45" }  ,
             new City() { Id = 46, Name = "Kahramanmaraş", OrderIndex = 46,PlateCode = "46" }  ,
             new City() { Id = 47, Name = "Mardin", OrderIndex = 47,PlateCode = "47" }  ,
             new City() { Id = 48, Name = "Muğla", OrderIndex = 48,PlateCode = "48" }  ,
             new City() { Id = 49, Name = "Muş", OrderIndex = 49,PlateCode = "49" }  ,
             new City() { Id = 50, Name = "Nevşehir", OrderIndex = 50,PlateCode = "50" }  ,
             new City() { Id = 51, Name = "Niğde", OrderIndex = 51,PlateCode = "51" }  ,
             new City() { Id = 52, Name = "Ordu", OrderIndex = 52,PlateCode = "52" }  ,
             new City() { Id = 53, Name = "Rize", OrderIndex = 53,PlateCode = "53" } , 
             new City() { Id = 54, Name = "Sakarya", OrderIndex = 54,PlateCode = "54" }  ,
             new City() { Id = 55, Name = "Samsun", OrderIndex = 55,PlateCode = "55" }  ,
             new City() { Id = 56, Name = "Siirt", OrderIndex = 56,PlateCode = "56" }  ,
             new City() { Id = 57, Name = "Sinop", OrderIndex = 57,PlateCode = "57" }  ,
             new City() { Id = 58, Name = "Sivas", OrderIndex = 58,PlateCode = "58" }  ,
             new City() { Id = 59, Name = "Tekirdağ", OrderIndex = 59,PlateCode = "59" }  ,
             new City() { Id = 60, Name = "Tokat", OrderIndex = 60,PlateCode = "60" }  ,
             new City() { Id = 61, Name = "Trabzon", OrderIndex = 61,PlateCode = "61" }  ,
             new City() { Id = 62, Name = "Tunceli", OrderIndex = 62,PlateCode = "62" }  ,
             new City() { Id = 63, Name = "Şanlıurfa", OrderIndex = 63,PlateCode = "63" } , 
             new City() { Id = 64, Name = "Uşak", OrderIndex = 64,PlateCode = "64" }  ,
             new City() { Id = 65, Name = "Van", OrderIndex = 65,PlateCode = "65" }  ,
             new City() { Id = 66, Name = "Yozgat", OrderIndex = 66,PlateCode = "66" }  ,
             new City() { Id = 67, Name = "Zonguldak", OrderIndex = 67,PlateCode = "67" }  ,
             new City() { Id = 68, Name = "Aksaray", OrderIndex = 68,PlateCode = "68" }  ,
             new City() { Id = 69, Name = "Bayburt", OrderIndex = 69,PlateCode = "69" }  ,
             new City() { Id = 70, Name = "Karaman", OrderIndex = 70,PlateCode = "70" }  ,
             new City() { Id = 71, Name = "Kırıkkale", OrderIndex = 71,PlateCode = "71" }  ,
             new City() { Id = 72, Name = "Batman", OrderIndex = 72,PlateCode = "72" }  ,
             new City() { Id = 73, Name = "Şırnak", OrderIndex = 73,PlateCode = "73" }  ,
             new City() { Id = 74, Name = "Bartın", OrderIndex = 74,PlateCode = "74" }  ,
             new City() { Id = 75, Name = "Ardahan", OrderIndex = 75,PlateCode = "75" }  ,
             new City() { Id = 76, Name = "Iğdır", OrderIndex = 76,PlateCode = "76" }  ,
             new City() { Id = 77, Name = "Yalova", OrderIndex = 77,PlateCode = "77" }  ,
             new City() { Id = 78, Name = "Karabük", OrderIndex = 78,PlateCode = "78" }  ,
             new City() { Id = 79, Name = "Kilis", OrderIndex = 79,PlateCode = "79" }  ,
             new City() { Id = 80, Name = "Osmaniye", OrderIndex = 80,PlateCode = "80" }  ,
             new City() { Id = 81, Name = "Düzce", OrderIndex = 81,PlateCode = "81" }  ,




        };

    }
}